#!/usr/bin/python3
from sys import argv
from math import sqrt
def factor(num):
    if num % 2 == 0:
        yield 2
        while num % 2 == 0:
            num //= 2
    for i in range(3, int(sqrt(num)) + 1, 2):
        if num % i == 0:
            yield i
            while num % i == 0:
                num //= i
    
    if num > 2:
        yield num


def main():
    if len(argv) != 2:
        print("Usage: factors <file>")
        return
    with open(argv[1], 'r') as f:
        for line in f:
            n = int(line.strip())
            p, q = factor(n)
            print(f"{n}={p}*{q}")


if __name__ == "__main__":
    main()
